/** Canonical Qatar area / neighborhood names for guest registration. */
export const QATAR_AREAS = [
  "Abu Dhalouf",
  "Abu Hamour",
  "Abu Samra",
  "Abu Sulba",
  "Ain Khaled",
  "Ain Sinan",
  "Airport Area",
  "Al Afja",
  "Al Aziziya",
  "Al Bidda",
  "Al Corniche",
  "Al Daayen",
  "Al Dafna",
  "Al Ebb",
  "Al Egla",
  "Al Furousiya",
  "Al Gharrafa",
  "Al Ghuwariyah",
  "Al Hilal",
  "Al Jasra",
  "Al Jemailiya",
  "Al Jeryan",
  "Al Karaana",
  "Al Kharaitiyat",
  "Al Kharayej",
  "Al Kharrara",
  "Al Kheesa",
  "Al Khor",
  "Al Khor City",
  "Al Khor Community",
  "Al Khor Industrial Area",
  "Al Khulaifat",
  "Al Luqta",
  "Al Mamoura",
  "Al Mansoura",
  "Al Markhiya",
  "Al Mashaf",
  "Al Masrouhiya",
  "Al Mearad",
  "Al Messila",
  "Al Mirqab",
  "Al Najada",
  "Al Nasraniya",
  "Al Qassar",
  "Al Rayyan",
  "Al Rufaa",
  "Al Sadd",
  "Al Sailiya",
  "Al Sakhama",
  "Al Seej",
  "Al Shagub",
  "Al Shahaniya",
  "Al Shamal",
  "Al Souq",
  "Al Tarfa",
  "Al Themaid",
  "Al Thakhira",
  "Al Thumama",
  "Al Utouriya",
  "Al Waab",
  "Al Wajbah",
  "Al Wakrah",
  "Al Wukair",
  "Al Zubarah",
  "Ar Ru'ays",
  "Aspire Park",
  "Aspire Zone",
  "Baaya",
  "Bani Hajer",
  "Barahat Al Jufairi",
  "Barwa Al Baraha",
  "Barwa Village",
  "Birkat Al Awamer",
  "Bu Fasseela",
  "Bu Samra",
  "Bu Sidra",
  "City Center",
  "Corniche",
  "Dahl Al Hamam",
  "Diplomatic Area",
  "Doha International Airport",
  "Doha Port",
  "Dukhan",
  "Duhail",
  "Education City",
  "Energy City",
  "Entertainment City",
  "Ezdan Village",
  "Fereej Abdel Aziz",
  "Fereej Al Amir",
  "Fereej Al Asiri",
  "Fereej Al Asmakh",
  "Fereej Al Ghanim",
  "Fereej Al Manaseer",
  "Fereej Al Murra",
  "Fereej Al Nasr",
  "Fereej Al Soudan",
  "Fereej Al Zaeem",
  "Fereej Bin Durham",
  "Fereej Bin Mahmoud",
  "Fereej Bin Omran",
  "Fereej Kulaib",
  "Fereej Mohammed Bin Jassim",
  "Film City",
  "Fox Hills",
  "Fuwayrit",
  "Fuwairit",
  "Gewan Island",
  "Gharrafat Al Rayyan",
  "Hamad International Airport",
  "Hamad Medical City",
  "Hazm Al Markhiya",
  "Industrial Area",
  "Izghawa",
  "Jabal Thuaileb",
  "Jelaiah",
  "Jeryan Jenaihat",
  "Jeryan Nejaima",
  "Jumailiyah",
  "Katara",
  "Khor Al Adaid",
  "Kharaitiyat",
  "Leabaib",
  "Lebday",
  "Legtaifiya",
  "Lejbailat",
  "Leqtaifiya",
  "Luaib",
  "Lusail",
  "Lusail Boulevard",
  "Lusail City",
  "Lusail Industrial Area",
  "Lusail Marina",
  "Lusail Towers",
  "Madinat Al Kaaban",
  "Madinat Al Shamal",
  "Madinat Khalifa North",
  "Madinat Khalifa South",
  "Marina District",
  "Mebaireek",
  "Mehairja",
  "Mesaieed",
  "Mesaieed Industrial Area",
  "Mesaieed Industrial City",
  "Mesaimeer",
  "Mina District",
  "Msheireb",
  "Muaither",
  "Muaither North",
  "Muaither South",
  "Muraikh",
  "Mushayrib",
  "Najma",
  "New Al Hitmi",
  "New Al Mirqab",
  "New Al Rayyan",
  "New Fereej Al Ghanim",
  "New Fereej Al Khulaifat",
  "New Muaither",
  "New Salata",
  "Nuaija",
  "Old Airport",
  "Old Al Ghanim",
  "Old Al Hitmi",
  "Old Al Rayyan",
  "Old Doha Port",
  "Onaiza",
  "Onaiza 63",
  "Place Vendôme Area",
  "Porto Arabia",
  "Purple Island Area",
  "Qanat Quartier",
  "Qatar Foundation",
  "Qetaifan Island North",
  "Qetaifan Island South",
  "Ras Abu Aboud",
  "Ras Abu Fontas",
  "Ras Laffan",
  "Ras Laffan Industrial City",
  "Rawdat Al Hamama",
  "Rawdat Al Khail",
  "Rawdat Egdaim",
  "Rawdat Rashed",
  "Rumaila",
  "Rumeilah",
  "Saina Al Humaidi",
  "Salata",
  "Salwa Road",
  "Sawda Natheel",
  "Shagra",
  "Shahaniya",
  "Simaisma",
  "Souq Waqif",
  "The Pearl-Qatar",
  "Traina",
  "Umm Al Amad",
  "Umm Al Houl",
  "Umm Al Seneem",
  "Umm Bab",
  "Umm Besher",
  "Umm Ebairiya",
  "Umm Ghuwailina",
  "Umm Lekhba",
  "Umm Qarn",
  "Umm Salal",
  "Umm Salal Ali",
  "Umm Salal Central",
  "Umm Salal Mohammed",
  "Villaggio Area",
  "Viva Bahriya",
  "Wadi Aba Seleel",
  "Wadi Al Banat",
  "Wadi Al Sail",
  "Wadi Al Wasaah",
  "Wadi Jallal",
  "Wadi Lusail",
  "Wakra South",
  "Waterfront District",
  "Waterfront Residential",
  "West Bay",
  "West Bay Lagoon",
  "Wholesale Market",
  "Wholesale Market Area",
  "Yasmeen City",
  "Zekreet",
  "Zubarah",
  "Other",
] as const;

export type QatarArea = (typeof QATAR_AREAS)[number];

export const QATAR_AREA_SET = new Set<string>(QATAR_AREAS);

export const QATAR_AREA_OPTIONS = QATAR_AREAS.map((name) => ({
  value: name,
  label: name,
}));

/** Include a previously saved value so admin edits of legacy zone numbers stay intact. */
export function qatarAreaSelectOptions(current?: string) {
  const extra = current?.trim() ?? "";
  if (extra && !QATAR_AREA_SET.has(extra)) {
    return [{ value: extra, label: extra }, ...QATAR_AREA_OPTIONS];
  }
  return QATAR_AREA_OPTIONS;
}
